### ISSUE TITLE
Uses data or not

### ISSUE THREAD

**Issue by sikhenevai** [interactionlab/android-notification-log#11]
Does this app use data or not? If I am turning off data for this app, it is being automatically turned on. But in the list of data usage this app is not being shown.

**Comment by weberdo** [comment]
If you are asking whether the app is sending data over WiFi or mobile, the answer is no. All data is stored on device only.

**Comment by sikhenevai** [comment]
No sir, it's not only about sending data. There is option for enable and disable data for this app. but it's not working properly.
